#!/bin/sh
#/ Usage: test
#/
#/ Run the tests.

set -e
cd $(dirname "$0")/..

[ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ] && {
    grep '^#/' <"$0"| cut -c4-
    exit 0
}

bundle exec rake test $@
